const {
  FIREBASE_PROJECT_ID,
  FIREBASE_DATABASE_URL,
  FIREBASE_COLLECTION,
  FIREBASE_DOC,
  FIREBASE_CONFIG_TYPE,
  FIREBASE_CONFIG_PRIVATE_KEY_ID,
  FIREBASE_CONFIG_PRIVATE_KEY,
  FIREBASE_CONFIG_EMAIL,
  FIREBASE_CONFIG_ID,
  FIREBASE_CONFIG_AUTH_URI,
  FIREBASE_CONFIG_TOKEN_URI,
  FIREBASE_CONFIG_AUTH_PROVIDER,
  FIREBASE_CONFIG_CLIENT,
} = process.env;

export const firebaseConfig = {
  databaseURL: FIREBASE_DATABASE_URL,
};

const credential = {
  type: FIREBASE_CONFIG_TYPE,
  project_id: FIREBASE_PROJECT_ID,
  private_key_id: FIREBASE_CONFIG_PRIVATE_KEY_ID,
  private_key: FIREBASE_CONFIG_PRIVATE_KEY.replace(/\\n/g, '\n'),
  client_email: FIREBASE_CONFIG_EMAIL,
  client_id: FIREBASE_CONFIG_ID,
  auth_uri: FIREBASE_CONFIG_AUTH_URI,
  token_uri: FIREBASE_CONFIG_TOKEN_URI,
  auth_provider_x509_cert_url: FIREBASE_CONFIG_AUTH_PROVIDER,
  client_x509_cert_url: FIREBASE_CONFIG_CLIENT,
}

export { FIREBASE_COLLECTION as firebaseCollection, FIREBASE_DOC as firebaseDoc, credential };
